baseURL = "https://adrien-f.github.io/thanos/"
languageCode = "en-us"
title = "Thanos - Highly available Prometheus setup with long term storage capabilities"
pygmentsCodeFences = true
pygmentsUseClasses = true
contentDir = "docs"
archetypeDir = "website/archetypes"
layoutDir = "website/layouts"
publishDir = "website/public"
staticDir = "website/static"

[params]
  SlackInvite = "https://join.slack.com/t/improbable-eng/shared_invite/enQtMzQ1ODcyMzQ5MjM4LWY5ZWZmNGM2ODc5MmViNmQ3ZTA3ZTY3NzQwOTBlMTkzZmIxZTIxODk0OWU3YjZhNWVlNDU3MDlkZGViZjhkMjc"
  GithubUser = "improbable-eng"
  GithubProject = "thanos"
  TwitterHandle = "ThanosMetrics"