apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: prom/prometheus:v2.0.0
        args: [
          "--config.file=/etc/prometheus/config/prometheus.yaml",
        ]
        name: prometheus
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/config
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
      terminationGracePeriodSeconds: 300